config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/generar_pdf', to: 'anticipos#generar_pdf', as: 'generar_pdf', format: :pdf
  get '/obras_por_arquitecto', to: 'obras#obras_por_arquitecto'
  get '/obras_por_arquitecto', to: 'anticipos#obras_por_arquitecto'

  delete 'anticipos/:id', to: 'anticipos#eliminar', as: 'eliminar_anticipo'



  root 'home#index'
  resources :home
  resources :anticipos
  resources :arquitectos
  resources :obras
end

app/models/arquitecto.rb
class Arquitecto < ApplicationRecord
  has_many :anticipos
  has_many :obras
end

app/controllers/arquitectos_controller.rb
class ArquitectosController < ApplicationController

  def index
    @arquitectos = Arquitecto.all
  end

  def new
    @arquitecto = Arquitecto.new
  end
  
  def create
    @arquitecto = Arquitecto.new(arquitecto_params)
    if @arquitecto.save
      redirect_to home_index_path
    else
      render 'new'
    end
  end

  private
  def arquitecto_params
    params.require(:arquitecto).permit(:nombre)
  end
end

app/helpers/arquitectos_helper.rb
module ArquitectosHelper
end

app/views/arquitectos/index.html.erb
<%= link_to "Arquitecto", new_arquitecto_path %>
<div class="table-responsive">
  <table class="table table-striped table-hover mx-auto w-50 shadow border border-dark border-2 bg-light text-dark">
    <thead class="bg-primary text-white">
      <tr>
        <th>Nombre</th>
      </tr>
    </thead>
    <tbody>
      <% @arquitectos.each do |arquitecto| %>
        <tr>
          <td><%= arquitecto.nombre %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/arquitectos/new.html.erb
<%= form_with model: @arquitecto, url: arquitectos_path, class: "form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :nombre %>
    <%= f.text_field :nombre, class: "form-control" %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>