config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/generar_pdf', to: 'anticipos#generar_pdf', as: 'generar_pdf', format: :pdf
  get '/obras_por_arquitecto', to: 'obras#obras_por_arquitecto'
  get '/obras_por_arquitecto', to: 'anticipos#obras_por_arquitecto'

  delete 'anticipos/:id', to: 'anticipos#eliminar', as: 'eliminar_anticipo'



  root 'home#index'
  resources :home
  resources :anticipos
  resources :arquitectos
  resources :obras
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    start_of_day = Time.zone.now.beginning_of_day
    end_of_day = Time.zone.now.end_of_day
    @anticipos = Anticipo.where(created_at: start_of_day..end_of_day).order(created_at: :desc)    
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= link_to "Crear anticipo", new_anticipo_path %>
<%= link_to "Arquitecto", arquitectos_path %>
<%= link_to "Obra", obras_path %>

<div class="table-responsive">
  <table class="table table-striped table-hover mx-auto w-50 shadow border border-dark border-2 bg-light text-dark">
    <thead class="bg-primary text-white">
      <tr>
        <th>Arquitecto</th>
        <th>Obra</th>
        <th>Fecha</th>
        <th>Cantidad</th>
        <th>Concepto</th>
        <th>Acciones</th> <!-- Agregamos una columna para las acciones -->
      </tr>
    </thead>
    <tbody>
      <% @anticipos.each do |anticipo| %>
        <tr>
          <td><%= anticipo.arquitecto.nombre %></td>
          <td><%= anticipo.obra.nombre %></td>
          <td><%= anticipo.fecha %></td>
          <td><%= anticipo.cantidad %></td>
          <td><%= anticipo.concepto %></td>
          <td>
            <%= link_to 'Generar PDF', generar_pdf_path(anticipo_id: anticipo.id, format: :pdf), class: 'btn btn-primary', target: '_blank' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>