config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

  get '/generar_pdf', to: 'anticipos#generar_pdf', as: 'generar_pdf', format: :pdf
  get '/obras_por_arquitecto', to: 'obras#obras_por_arquitecto'
  get '/obras_por_arquitecto', to: 'anticipos#obras_por_arquitecto'

  delete 'anticipos/:id', to: 'anticipos#eliminar', as: 'eliminar_anticipo'



  root 'home#index'
  resources :home
  resources :anticipos
  resources :arquitectos
  resources :obras
end

app/models/obra.rb
class Obra < ApplicationRecord
  has_many :anticipos
  belongs_to :arquitecto
end

app/controllers/obras_controller.rb
class ObrasController < ApplicationController
  def index
    @obras = Obra.order(:nombre)
  end

  def new
    @obra = Obra.new
    @arquitectos = Arquitecto.all
  end
  
  def create
    @obra = Obra.new(obra_params)
    if @obra.save
      redirect_to home_index_path
    else
      render 'new'
    end
  end

  def obras_por_arquitecto
    arquitecto_id = params[:arquitecto_id]
    obras = Obra.where(arquitecto_id: arquitecto_id)

    render json: { obras: obras }
  end

  private
  def obra_params
    params.require(:obra).permit(:nombre, :arquitecto_id, :estado)
  end
end

app/helpers/obras_helper.rb
module ObrasHelper
end

app/views/obras/index.html.erb
<%= link_to "Obra", new_obra_path %>
<div class="table-responsive">
  <table class="table table-striped table-hover mx-auto w-50 shadow border border-dark border-2 bg-light text-dark">
    <thead class="bg-primary text-white">
      <tr>
        <th>Nombre</th>
        <th>Arquitecto</th>
      </tr>
    </thead>
    <tbody>
      <% @obras.each do |obra| %>
        <tr>
          <td><%= obra.nombre %></td>
          <td><%= obra.arquitecto.nombre %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/obras/new.html.erb
<%= form_with model: @obra, url: obras_path, class: "form-horizontal" do |f| %>
  <div class="form-group">
    <%= f.label :Nombre %>
    <%= f.text_field :nombre, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Arquitecto, class: "d-block" %>
    <%= f.select :arquitecto_id, options_for_select(@arquitectos.map { |arquitecto| [arquitecto.nombre, arquitecto.id] }), {}, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :Estatus %>
    <%= f.text_field :estado, class: "form-control" %>
  </div>

  <div class="form-group text-center">
    <%= f.submit "Guardar", class: "btn btn-primary" %>
  </div>
<% end %>